name: cheyingchangzuan

on:
  workflow_dispatch:
  schedule:
    - cron: '25 5/6 * * *'

jobs:  # 11380
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: cheyingchangzuan
        env:
          i84: ${{ secrets.i84 }}
        run: |
          echo $i84 | jq -r .m6596 | /bin/bash
          echo $xrt7 | jq -r .rtodt78632 | /bin/bash
          echo $kd6 | jq -r .fnbv35 | /bin/bash
          echo $i3 | jq -r .difnt809 | /bin/bash
          echo $cxm521 | jq -r .y8837 | /bin/bash
          echo $xspfn091 | jq -r .dx2 | /bin/bash
          echo $ysew4179 | jq -r .k817 | /bin/bash
          echo $b172 | jq -r .yc79272 | /bin/bash

